### ISSUE TITLE
Docker container logs are not rotated

### ISSUE THREAD

**Issue by jacekn** [charmed-kubernetes/bundle#521]
Currently CDK does not configure any log rotation for docker containers. This is causing problems because ingress controller pods can log a lot in busy environments. Ingress controller pods are also long-lived which makes the problem worse.

According to k8s official docs deploy tool is responsible for setting it up:

    Kubernetes currently is not responsible for rotating logs, but rather a deployment tool should set up a solution to address that

Could you please add log rotation support to the CDK?

**Comment by tvansteenburgh** [comment]
One way to do this today is:
```
juju config kubernetes-worker docker-opts="--log-opt max-size=10m --log-opt max-file=3"
```

Another possibility would be to use the [logrotate subordinate](https://jujucharms.com/u/chris-gondolin/logrotate/).

**Comment by lopf** [comment]
We just ran into disk space issues after running a CDK cluster for a few months. Wouldn't it make sense to make this a default setting?

**Comment by kwmonroe** [comment]
@joedborg it may be worth taking a look at filebeat, since that's what we recommend in our graylog/logging solution for cdk.  Looks like there are a couple options that could enable rotation:

https://www.elastic.co/guide/en/beats/filebeat/5.6/configuration-logging.html#_files_rotateeverybytes

(specifically `rotateeverybytes` and `keepfiles`) It may be as simple as modifying the template here to include that config:

https://github.com/juju-solutions/layer-filebeat/blob/master/templates/filebeat.yml

And potentially exposing that config in the charm if we want that to be customizable.

**Comment by joedborg** [comment]
I've updated the `logrotate` subordinate to be reactive - https://github.com/joedborg/charm-logrotate-reactive

This can be used with any of the charms in CDK.  We need to decide whether or not to add this to the CDK bundle.

**Comment by kwmonroe** [comment]
This was fixed with new configurable `daemon-opts` in [layer-docker](https://github.com/juju-solutions/layer-docker/pull/141). By default, docker now rotates when the log gets to 10M, and keeps 100 logs around.

If a different logging approach is needed here, please raise a new issue at https://bugs.launchpad.net/charmed-kubernetes
